[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "telco-churn-pipeline"
version = "0.1.0"
description = "Predictive Churn Pipeline and ROI Engine"
dependencies = [
    "pandas",
    "numpy",
    "scikit-learn",
    "xgboost",
    "shap",
    "kaggle",
    "pandera",
    "matplotlib",
    "fastapi",
    "uvicorn",
    "streamlit",
    "requests"
]