[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "telco_churn_roi_pipeline"
version = "0.1.0"
description = "MLOps Pipeline for Telco Churn"
requires-python = ">=3.9"
dependencies = [
    "pandas",
    "numpy",
    "scikit-learn",
    "xgboost",
    "shap",
    "kaggle",
    "pandera",
    "matplotlib"
    "fastapi",
    "uvicorn",
    "streamlit",
    "requests"
]
